### ISSUE TITLE
The task.request is still sometimes "empty"

### ISSUE THREAD

**Issue by ShaheedHaque** [the-wondersmith/celery-aio-pool#2]
Despite 3f7b833f3, I am still getting this "sometimes":

```
billiard.einfo.ExceptionWithTraceback:
"""
Traceback (most recent call last):
  File "/main/srhaque/bootstrap/source/paiyroll/tasks.py", line 109, in viewflow_dequeue
    return CeleryResultCodec.encode_success(logger, celery_task, body(call_, viewflow_process, viewflow_task, celery_task))
  File "/main/srhaque/bootstrap/source/paiyroll/tasks.py", line 96, in body
    assert cl_task.request.id == vf_task.external_task_id, \
AssertionError: None != external task 09db61b7-f45b-4f1d-8752-6acadad2076e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery_aio_pool/tracer.py", line 283, in trace_task
    R = retval = AsyncIOPool.run_in_pool(fun, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery_aio_pool/pool.py", line 222, in run_in_pool
    return worker_pool.run(
  File "/usr/local/lib/python3.10/dist-packages/celery_aio_pool/pool.py", line 203, in run
    raise error
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 732, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/app/task.py", line 405, in __call__
    return self.run(*args, **kwargs)
  File "/main/srhaque/bootstrap/source/paiyroll/tasks.py", line 112, in viewflow_dequeue
    return CeleryResultCodec.encode_exception(logger, celery_task, e)
  File "/main/srhaque/bootstrap/source/paiyroll/xprocess.py", line 336, in encode_exception
    return cls._encode(logger, celery_states.FAILURE, celery_task, exception)
  File "/main/srhaque/bootstrap/source/paiyroll/xprocess.py", line 345, in _encode
    hostname = request.hostname.split('@', 1)[-1]
AttributeError: 'NoneType' object has no attribute 'split'
"""
```

As we discussed at one point, it seems there are multiple paths into the user's logic and at least one of these paths is clearing or recreating the `task.request`.

**Comment by ShaheedHaque** [comment]
(Forget the ~~sometimes~~ mentioned above. I think it happens all the time for me.)

I have tracked the failure down to something related to the `_install_stack_protection` function here: https://github.com/celery/celery/blob/bfd8587ddbf44b945c67441ceb70458a4385154e/celery/app/trace.py#L708. This does the following:

```
  BaseTask.__call__ = __protected_call__
```

to install its `__protected_call__`; if I skip over this monkey patching line, the `task.request.hostname` and it's siblings all work as I expect; that is to say `task.request` is a fully populated `celery.app.trace.Context` object. Now, the `__protected_call__` method does some black magic equivalent to this:

```
def __protected_call__():
    ...stuff...
    if ...stuff...:
        return self.run(*args, **kwargs)
    else:
        return orig(self, *args, **kwargs)
```

such that we end up calling through `orig`. This ends up creating a new, incomplete, `celery.app.trace.Context`. I believe the problem is something to do with the logic in this area...but I cannot quite see the wood for the trees.

**Comment by ShaheedHaque** [comment]
I just found that this can happen in vanilla celery. I'm not sure of the reasons why, but at least this exonerates celery-aio-pool.
